import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowLeft, BadgeCheck, CheckCircle2, ExternalLink, Globe2, HeartPulse, Link2, ShieldAlert, UserRound } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAccount } from "wagmi";
import { api, messageFromError } from "@/lib/api";
import { AgentAvatar } from "@/components/AgentAvatar";
import { AgentMetadataEditor } from "@/components/AgentMetadataEditor";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { scanAgentUrl } from "@/lib/erc8004";

type Detail=Record<string,any>;
// Every service the registration publishes, read from both places 8004scan
// keeps them. Rendering only its normalised map reported "1 declared" for an
// agent whose own metadata listed two.
type Svc={name:string;endpoint:string;version?:string|null;tool_count?:number|null;skill_count?:number|null};
const show=(value:any)=>value===null||value===undefined||value===""?"Unavailable":String(value);

export default function OnchainDetailPage(){
  const {network="mainnet",tokenId="0"}=useParams(); const net=network as "mainnet"|"testnet"; const {address}=useAccount(); const [data,setData]=useState<{agent:Detail;feedbacks:Detail[];source:string;verdict?:{status:string;note?:string;activatable:boolean;checked_at?:string;endpoint_kind?:string;declared_endpoint?:string;called_url?:string}|null}|null>(null); const [error,setError]=useState(""); const [editing,setEditing]=useState(false);
  useEffect(()=>{api.get(`/onchain/agent-details/${network}/${tokenId}`).then(r=>setData(r.data)).catch(e=>setError(messageFromError(e)))},[network,tokenId]);
  const agent=data?.agent; const isOwner=!!address&&agent?.owner_address?.toLowerCase()===address.toLowerCase(); const services=useMemo(()=>(agent?.declared_services as Svc[])||[],[agent]);
  if(error)return <div className="page-wrap wallet-empty" data-testid="agent-detail-error"><ShieldAlert size={30}/><h1>Agent detail unavailable</h1><p>{error}</p><Button asChild><Link to="/onchain">Back to Onchain</Link></Button></div>;
  if(!agent)return <div className="page-wrap detail-loading" data-testid="onchain-detail-loading"><Skeleton className="h-48"/><Skeleton className="h-96"/></div>;
  const initial={name:agent.name,description:agent.description,image:"",serviceName:agent.supported_protocols?.[0]||"Web",serviceEndpoint:agent.agent_url||agent.a2a_endpoint||agent.mcp_server||"",serviceVersion:agent.a2a_version||agent.mcp_version||"1.0.0",x402Support:agent.x402_supported,active:agent.is_active!==false,supportedTrust:(agent.supported_trust_models||[]).join(", ")};
  return <div className="page-wrap onchain-detail-page"><Link to="/onchain" className="back-link" data-testid="back-onchain"><ArrowLeft size={15}/> Onchain explorer</Link><section className="detail-hero"><AgentAvatar name={`${agent.chain_id}-${agent.token_id}-${agent.name}`} size={76} src={`${process.env.REACT_APP_BACKEND_URL}/api/onchain/agents/${net}/${agent.token_id}/icon`} testId="onchain-detail-avatar"/><div><div className="detail-title"><h1 data-testid="onchain-detail-name">{agent.name}</h1>{agent.is_verified&&<BadgeCheck size={19}/>}</div><p data-testid="onchain-detail-description">{agent.description}</p><div className="capability-row">{agent.supported_protocols.map((x:string)=><span key={x}>{x}</span>)}</div></div><div className="detail-actions"><a data-testid="manage-on-8004scan-link" href={scanAgentUrl(net,agent.token_id)} target="_blank" rel="noreferrer">Manage on 8004scan <ExternalLink size={14}/></a>{isOwner&&<Button data-testid="edit-agent-metadata-button" onClick={()=>setEditing(x=>!x)}>{editing?"Close editor":"Edit metadata"}</Button>}</div></section>
    <div className="detail-score-band"><div><strong data-testid="detail-source-score">{show(agent.total_score)}</strong><span>8004scan score</span></div><div><strong data-testid="detail-network-rank">{agent.rank?`#${agent.rank}`:"—"}</strong><span>Network rank</span></div><div><strong data-testid="detail-health-score">{show(agent.health_score)}</strong><span>Health score</span></div><div><strong data-testid="detail-feedback-total">{agent.total_feedbacks}</strong><span>Feedbacks</span></div><div><strong data-testid="detail-validation-total">{agent.successful_validations}/{agent.total_validations}</strong><span>Validations</span></div></div>
    {editing&&<AgentMetadataEditor mode="edit" network={net} tokenId={agent.token_id} initial={initial}/>}<div className="detail-columns"><div><section className="detail-section"><div className="section-title"><h2><UserRound size={17}/> Identity & ownership</h2></div><div className="detail-kv"><div><span>Owner</span><strong data-testid="detail-owner-address">{show(agent.owner_address)}</strong></div><div><span>Creator</span><strong>{show(agent.creator_address)}</strong></div><div><span>Agent wallet</span><strong>{show(agent.agent_wallet)}</strong></div><div><span>Identity registry</span><strong>{show(agent.contract_address)}</strong></div><div><span>Token ID</span><strong>#{agent.token_id}</strong></div><div><span>Network</span><strong>{net==="testnet"?"BSC Testnet · 97":"BSC Mainnet · 56"}</strong></div></div></section><section className="detail-section"><div className="section-title"><h2><Globe2 size={17}/> Services & endpoints</h2><Badge>{services.length} declared</Badge></div><div className="service-list" data-testid="detail-services">{services.length?services.map(svc=><div key={svc.endpoint} className={svc.endpoint===data.verdict?.declared_endpoint?"probed":undefined}><strong>{svc.name}{svc.version&&<span className="svc-version">v{svc.version}</span>}{/* Marking the one we tested is what makes the verdict below attributable — an agent can declare several endpoints and we call one. */}{svc.endpoint===data.verdict?.declared_endpoint&&<span className="svc-probed" data-testid="detail-service-probed">tested below</span>}</strong><code>{svc.endpoint}</code>{(svc.tool_count||svc.skill_count)&&<em>{svc.tool_count?`${svc.tool_count} tools declared`:`${svc.skill_count} skills declared`}</em>}</div>):<p>No service details supplied.</p>}</div>{/* 8004scan reports an agent "Active" from its on-chain state, which says the
    registration exists — not that anything answers. This is the other half:
    what happened when AgentDock last called the endpoint. */}
{data.verdict
  ? <div className="endpoint-state" data-testid="detail-endpoint-verdict"><span className={data.verdict.activatable?"ok":"warn"}>{data.verdict.activatable?<CheckCircle2 size={14}/>:<ShieldAlert size={14}/>}</span><div><strong>{data.verdict.activatable?`AgentDock called this ${data.verdict.endpoint_kind?.toUpperCase()||""} endpoint and it answered`:"AgentDock called this endpoint and it did not answer usably"}</strong><p>{data.verdict.note}{data.verdict.checked_at&&<em> · checked {new Date(data.verdict.checked_at).toLocaleString()}</em>}</p>{/* The published URL is often not a legal request: an id template has to be filled in, and an agent card has to be followed. Naming the URL we reached is the difference between a verdict and an assertion. */}{data.verdict.called_url&&data.verdict.called_url!==data.verdict.declared_endpoint&&<code className="called-url" data-testid="detail-called-url">called {data.verdict.called_url}</code>}</div></div>
  : <div className="endpoint-state" data-testid="detail-endpoint-verdict"><span className="warn"><ShieldAlert size={14}/></span><div><strong>Not called yet</strong><p>AgentDock has not probed this endpoint, so nothing here claims it works.</p></div></div>}</section><section className="detail-section"><div className="section-title"><h2><Link2 size={17}/> Onchain provenance</h2></div><div className="detail-kv"><div><span>Created block</span><strong>{show(agent.created_block_number)}</strong></div><div><span>Created transaction</span><strong>{agent.created_tx_hash?<a href={`${net==="testnet"?"https://testnet.bscscan.com":"https://bscscan.com"}/tx/${agent.created_tx_hash}`} target="_blank" rel="noreferrer">{agent.created_tx_hash.slice(0,10)}… <ExternalLink size={12}/></a>:"Unavailable"}</strong></div><div><span>Source</span><strong>{data.source}</strong></div><div><span>Parse status</span><strong>{show(agent.parse_status?.status)}</strong></div></div></section></div>
      <aside><section className="detail-section"><div className="section-title"><h2><HeartPulse size={17}/> Trust signals</h2></div><div className="trust-list"><div><span>Active claim</span><strong>{agent.is_active===true?"Active":agent.is_active===false?"Inactive":"Unavailable"}</strong></div><div><span>x402 claim</span><strong>{agent.x402_supported?"Declared":"Not declared"}</strong></div><div><span>Average feedback</span><strong>{show(agent.average_score)}</strong></div><div><span>Quality</span><strong>{show(agent.quality_score)}</strong></div><div><span>Popularity</span><strong>{show(agent.popularity_score)}</strong></div><div><span>Metadata completeness</span><strong>{show(agent.metadata_completeness_score)}</strong></div></div></section><section className="detail-section"><div className="section-title"><h2><Activity size={17}/> Recent feedback</h2><Badge>{data.feedbacks.length}</Badge></div><div className="feedback-list" data-testid="detail-feedback-list">{data.feedbacks.length?data.feedbacks.map(item=><article key={item.feedback_id}><div><strong>{show(item.score)}</strong><span>{item.submitted_at?new Date(item.submitted_at).toLocaleDateString():""}</span></div><p>{item.comment||"No comment supplied"}</p></article>):<p>No indexed feedback for this agent.</p>}</div></section></aside></div>
  </div>;
}