import { useEffect, useMemo, useState } from "react";
import { Activity, BadgeCheck, Database, ExternalLink, Search, ShieldQuestion, Zap } from "lucide-react";
import { api } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { AgentAvatar } from "@/components/AgentAvatar";

type LiveAgent = { id:string; chain_id:number; is_testnet:boolean; token_id:number; name:string; description:string; image_url?:string; has_source_icon:boolean; owner_address?:string; contract_address?:string; supported_protocols:string[]; x402_supported:boolean; is_verified:boolean; total_score?:number; rank?:number; health_score?:number; total_feedbacks:number; average_score?:number; source_label:string; synced_at:string };
type SyncStatus = { status:string; imported?:number; feedback_sample?:number; available_total?:number; sample_limit?:number; completed_at?:string; rate_limit?:{limit?:string;remaining?:string}; error?:string };

const compact = (value?:number) => typeof value === "number" ? Intl.NumberFormat("en", { notation:"compact", maximumFractionDigits:1 }).format(value) : "—";

export default function OnchainPage() {
  const [agents,setAgents] = useState<LiveAgent[]>([]); const [status,setStatus] = useState<SyncStatus>({status:"loading"}); const [loading,setLoading] = useState(true);
  const [loadError,setLoadError] = useState("");
  const [network,setNetwork] = useState("mainnet");
  const [search,setSearch] = useState(""); const [protocol,setProtocol] = useState("all"); const [x402,setX402] = useState("all"); const [sort,setSort] = useState("score");
  useEffect(()=>{
    let active=true; let timer:ReturnType<typeof setTimeout>;
    setLoading(true);
    const load=async()=>{ try { const [a,s]=await Promise.all([api.get(`/onchain/agents?network=${network}`),api.get(`/integrations/8004scan/status?network=${network}`)]); if(!active)return; setAgents(a.data.items); setStatus(s.data); setLoadError(""); setLoading(false); if(["loading","running","never_run"].includes(s.data.status)) timer=setTimeout(load,2000); } catch { if(active){setLoadError("Live registry data is temporarily unavailable.");setLoading(false);} } };
    load(); return()=>{active=false;clearTimeout(timer)};
  },[network]);
  const protocols=useMemo(()=>Array.from(new Set(agents.flatMap(a=>a.supported_protocols))).sort(),[agents]);
  const visible=useMemo(()=>agents.filter(a=>(protocol==="all"||a.supported_protocols.includes(protocol))&&(x402==="all"||a.x402_supported===(x402==="yes"))&&`${a.name} ${a.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="rank"?(a.rank??999999)-(b.rank??999999):sort==="feedback"?b.total_feedbacks-a.total_feedbacks:(b.total_score??-1)-(a.total_score??-1)),[agents,search,protocol,x402,sort]);
  const changeNetwork=(value:string)=>{setNetwork(value);setSearch("");setProtocol("all");setX402("all");setSort("score")};
  const backendUrl=process.env.REACT_APP_BACKEND_URL;
  return <div className="page-wrap onchain-page">
    <section className="onchain-heading"><div><p className="section-kicker"><Database size={14}/> Live registry data</p><h1 data-testid="onchain-heading">BSC {network === "testnet" ? "Testnet" : "Mainnet"} agents,<br/>direct from 8004scan.</h1><p data-testid="onchain-subheading">Identity, metadata, protocol, x402, score, and feedback observations are preserved as supplied—not treated as measured AgentDock performance.</p></div><div className="sync-panel" data-testid="scan-sync-status"><span className={`sync-dot ${status.status}`}/><div><strong>{status.status === "success" ? "Synchronized" : status.status}</strong><small>{status.imported ?? 0} agents · {status.feedback_sample ?? 0} feedbacks</small></div><Badge>{compact(status.available_total)} available</Badge></div></section>
    <div className="onchain-note" data-testid="onchain-source-note"><ShieldQuestion size={17}/><span>Viewing BSC {network === "testnet" ? "Testnet" : "Mainnet"} source records. Mainnet identity discovery does not enable production payments.</span></div>
    <div className="onchain-tools expanded"><div className="onchain-search"><Search size={17}/><Input data-testid="onchain-search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search live agent names or descriptions"/></div><Select value={network} onValueChange={changeNetwork}><SelectTrigger data-testid="onchain-network-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem data-testid="network-mainnet-option" value="mainnet">BSC Mainnet</SelectItem><SelectItem data-testid="network-testnet-option" value="testnet">BSC Testnet</SelectItem></SelectContent></Select><Select value={protocol} onValueChange={setProtocol}><SelectTrigger data-testid="onchain-protocol-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem data-testid="protocol-all-option" value="all">All protocols</SelectItem>{protocols.map(p=><SelectItem data-testid={`protocol-${p.toLowerCase()}-option`} value={p} key={p}>{p}</SelectItem>)}</SelectContent></Select><Select value={x402} onValueChange={setX402}><SelectTrigger data-testid="onchain-x402-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem data-testid="x402-all-option" value="all">Any payment support</SelectItem><SelectItem data-testid="x402-yes-option" value="yes">x402 claimed</SelectItem><SelectItem data-testid="x402-no-option" value="no">No x402 claim</SelectItem></SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger data-testid="onchain-sort-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem data-testid="sort-score-option" value="score">8004scan score</SelectItem><SelectItem data-testid="sort-rank-option" value="rank">Network rank</SelectItem><SelectItem data-testid="sort-feedback-option" value="feedback">Feedback volume</SelectItem></SelectContent></Select></div>
    <div className="onchain-count"><span data-testid="onchain-result-count">{visible.length} synchronized agents</span><span>Updated {status.completed_at ? new Date(status.completed_at).toLocaleString() : "pending"}</span></div>
    {loadError&&<div className="integration-notice" data-testid="onchain-load-error"><ShieldQuestion size={17}/><strong>{loadError}</strong></div>}
    {loading?<div className="onchain-grid">{[1,2,3,4,5,6].map(x=><Skeleton className="h-72" key={x}/>)}</div>:<div className="onchain-grid" data-testid="onchain-agent-grid">{visible.map(agent=><article className="onchain-card" data-testid={`onchain-agent-${agent.token_id}`} key={agent.id}>
      <div className="onchain-card-top"><AgentAvatar name={`${agent.chain_id}-${agent.token_id}-${agent.name}`} testId={`onchain-avatar-${agent.token_id}`} src={agent.has_source_icon?`${backendUrl}/api/onchain/agents/${network}/${agent.token_id}/icon`:undefined}/><div><div className="onchain-name"><h2 data-testid={`onchain-name-${agent.token_id}`}>{agent.name}</h2>{agent.is_verified&&<BadgeCheck size={15}/>}</div><span data-testid={`onchain-id-${agent.token_id}`}>ERC-8004 #{agent.token_id}</span></div>{agent.x402_supported&&<Badge data-testid={`onchain-x402-${agent.token_id}`} className="x402-badge"><Zap size={10}/> x402 claim</Badge>}</div>
      <p data-testid={`onchain-description-${agent.token_id}`}>{agent.description}</p><div className="protocol-list" data-testid={`onchain-protocols-${agent.token_id}`}>{agent.supported_protocols.length?agent.supported_protocols.map(p=><span key={p}>{p}</span>):<span>No protocol declared</span>}</div>
      <div className="onchain-metrics"><div><strong data-testid={`onchain-score-${agent.token_id}`}>{agent.total_score ?? "—"}</strong><span>8004scan score</span></div><div><strong data-testid={`onchain-rank-${agent.token_id}`}>{agent.rank ? `#${agent.rank}` : "—"}</strong><span>Network rank</span></div><div><strong data-testid={`onchain-feedback-${agent.token_id}`}>{compact(agent.total_feedbacks)}</strong><span>Feedbacks</span></div></div>
      <div className="onchain-footer"><span><Activity size={12}/>{agent.source_label}</span>{agent.contract_address&&<a data-testid={`onchain-contract-${agent.token_id}`} href={`${agent.is_testnet ? "https://testnet.bscscan.com" : "https://bscscan.com"}/address/${agent.contract_address}`} target="_blank" rel="noreferrer" aria-label="View contract on BscScan"><ExternalLink size={14}/></a>}</div>
    </article>)}</div>}
  </div>;
}